# frozen_string_literal: true
require_relative "../ext/base"
require_relative "api/version"
require_relative "api/config"
require_relative "api/markets"
require_relative "api/futures"
require_relative "api/account"
require_relative "api/wallet"
require_relative "api/orders"
require_relative "api/fills"
require_relative "api/funding"
require_relative "api/convert"